// Valid Anagrams 
// https://leetcode.com/problems/group-anagrams/

// Algorithm 
// 1. Create a Hashmap to Store Specfic Key -> Anagrams 

// 2. Traverse the Array 
// 3. Generate a unique key for each Anagram (Unique Key is generated by keeping a count of the letters occured and making a string using the count + '# for each letter)
// 4. Add the Anagram to the relevant key generated

// 5. Travere the Hashmap and add the Vector of Anagrams to the Ans vector
// 6. Return Ans

string getKey(string str) {
        vector<int> count(26);
        for (int i = 0; i < str.length(); i++) {
            count[str[i] - 'a']++;
        }
        string key = "";
        for (int i = 0; i < 26; i++) {
            key += to_string(count[i] + '#');
        }
        return key;
    }

    vector<vector<string>> groupAnagrams(vector<string>& strs) {
        unordered_map<string, vector<string>> check;
        for (int i = 0; i < strs.size(); i++) {
            string str = getKey(strs[i]);
            check[str].push_back(strs[i]);
        }
        vector<vector<string>> ans;
        for (auto& pair : check) {
            ans.push_back(pair.second);
        }
        return ans;
    }